// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBViTHXk8NBFhzWgL72X8hm2B5wJn_wbNg',
    appId: '1:78529146451:web:d33602acf30d57aaa2e0a6',
    messagingSenderId: '78529146451',
    projectId: 'flutter-chatting-75ec2',
    authDomain: 'flutter-chatting-75ec2.firebaseapp.com',
    storageBucket: 'flutter-chatting-75ec2.appspot.com',
    measurementId: 'G-13EE1NTXLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPPfAZAtrSApzQtzXf6GZUIls6u57HPAc',
    appId: '1:78529146451:android:adca4d2e276bed46a2e0a6',
    messagingSenderId: '78529146451',
    projectId: 'flutter-chatting-75ec2',
    storageBucket: 'flutter-chatting-75ec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeC59XjqBXT8KmYctnfZH52-DfBa10X0Y',
    appId: '1:78529146451:ios:341f27afd1aacf02a2e0a6',
    messagingSenderId: '78529146451',
    projectId: 'flutter-chatting-75ec2',
    storageBucket: 'flutter-chatting-75ec2.appspot.com',
    iosClientId: '78529146451-m65040o77fe11uea1j0g4h4s48aqn64p.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.dicodingChatting',
  );
}
